---
# Manage Galaxy clone

- name: Update Galaxy to specified ref
  git:
    dest: "{{ galaxy_server_dir }}"
    force: "{{ galaxy_force_checkout }}"
    repo: "{{ galaxy_repo }}"
    version: "{{ galaxy_commit_id }}"
    executable: "{{ git_executable | default(omit) }}"
  register: __galaxy_git_update_result
  notify:
    - restart galaxy
    - email administrator with commit id

- name: Report Galaxy version change
  debug:
    msg: "Galaxy version changed from '{{ __galaxy_git_update_result.before }}' to '{{ __galaxy_git_update_result.after }}'"
  changed_when: __galaxy_git_update_result is changed
  when: __galaxy_git_update_result is changed

- name: Include virtualenv setup tasks
  include_tasks: virtualenv.yml

- name: Remove orphaned .pyc files and compile bytecode
  script: "makepyc.py {{ galaxy_server_dir }}/lib"
  environment:
    PATH: "{{ galaxy_venv_dir }}/bin"
  when: __galaxy_git_update_result is changed
