---
# main tasks file for galaxyproject.galaxy

# Deploy a Galaxy server
#   https://docs.galaxyproject.org/

- name: Import layout variable tasks
  import_tasks: layout.yml

- name: Include user creation tasks
  include_tasks: user.yml
  when: galaxy_create_user or galaxy_create_privsep_user
  tags:
    - galaxy_create_user

- name: Include path management tasks
  include_tasks: paths.yml
  when: galaxy_manage_paths
  tags:
    - galaxy_manage_paths

- name: Include clone tasks
  include_tasks: clone.yml
  when: galaxy_manage_clone
  tags:
    - galaxy_manage_clone

- name: Include download tasks
  include_tasks: download.yml
  when: not galaxy_manage_clone and galaxy_manage_download
  tags:
    - galaxy_manage_download

- name: Include static config setup tasks
  include_tasks: static_setup.yml
  when: galaxy_manage_static_setup
  tags: 
    - galaxy_config_files

- name: Include dependency setup tasks
  include_tasks: dependencies.yml
  when: galaxy_fetch_dependencies
  tags:
    - galaxy_fetch_dependencies

- name: Include mutable config setup tasks
  include_tasks: mutable_setup.yml
  when: galaxy_manage_mutable_setup
  tags:
    - galaxy_manage_mutable_setup

- name: Include database management tasks
  include_tasks: database.yml
  when: galaxy_manage_database
  tags:
    - galaxy_manage_database

- name: Include error document setup tasks
  include_tasks: errordocs.yml
  when: galaxy_manage_errordocs
  tags:
    - galaxy_manage_errordocs
